# encoding: utf-8
puts "To handle exceptions in ruby you have to create a kind of try/catch method ( from java )"
puts "but in ruby you use begin/rescue, like this"
puts "----------------------------------------------------------------------------------------"
puts "begin"
puts "  method_that_will_raise_exception"
puts "rescue"
puts "  puts 'get the exception and do somethings with that'"
puts "end"
puts "----------------------------------------------------------------------------------------"
puts "All the instructions between begin and rescue will be secure and if anything goes wrong "
puts " the rescue block will be called"
puts "You can capture with type of exception the rescue will be handling to a better error    "
puts " handling, see"
puts "----------------------------------------------------------------------------------------"
puts "begin"
puts "  method_that_will_raise_exception"
puts "rescue MyGreatError"
puts "  puts 'get the exception and do somethings with that'"
puts "end"
puts "----------------------------------------------------------------------------------------"
puts "With that the rescue will be called if the error is of the type MyGreatError"
puts "To get the error object in a variable in the rescue block you need to set a var in the  "
puts "following way"
puts "----------------------------------------------------------------------------------------"
puts "begin"
puts "  method_that_will_raise_exception"
puts "rescue MyGreatError => err"
puts "  puts 'get the exception and do somethings with that'"
puts "end"
puts "----------------------------------------------------------------------------------------"
puts "With that inside the rescue block you will have acess to err variable that contains the "
puts "exception obejct"
puts "You can also have a block that will aways be executed, if there is no exception or with "
puts "exception, you can achieve this with the ensure block"
puts "----------------------------------------------------------------------------------------"
puts "begin"
puts "  method_that_will_raise_exception"
puts "rescue MyGreatError => err"
puts "  puts 'get the exception and do somethings with that'"
puts "ensure"
puts "  puts 'it will aways be executed'"
puts "end"